//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Item_Price { get; set; }
        public Nullable<int> Item_Amount { get; set; }
        public Nullable<int> Item_Supplier_ID { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
